click_after_warp = true
hint_source = "static"
hint_chars = "abcdefghijklmnopqrstuvwxyz"
hint_bgcolor = "#1e1e2e"
hint_bg_opacity = 1.0
hint_fgcolor = "#cdd6f4"
hint_border_radius = 4.0
hint_font = "monospace"
hint_font_size = 16.0
hint_grid_gap = 80
grid_color = "#89b4fa"
grid_border_size = 2
grid_font_size = 36.0
grid_min_size = 270.0
grid_quadrant_keys = [
    "u",
    "i",
    "j",
    "k",
]
speed = 220
acceleration = 700
normal_move_keys = [
    "h",
    "j",
    "k",
    "l",
]
speed_modifier_key = "SHIFT"
speed_modifier_multiplier = 5.0
cursor_color = "#f38ba8"
cursor_size = 7
crosshair_line_width = 2
buttons = [
    "m",
    ",",
    ".",
]
